/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genscann;

import AnalizadorEntrada.CargarArchivo;
import AnalizadorEntrada.Globales;
import Generador.CodificarCPlusPlus;
import Generador.CodificarCSharp;
import Modelos.Accion;
import Modelos.Conjunto;
import Modelos.ExpresionCompleta;
import Modelos.Token;
import static genscann.GenScann.*;
import java.awt.FileDialog;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Axel Rodriguez
 */
public class Principal extends javax.swing.JFrame {

    // Models
    DefaultListModel<String> nombreConjuntos = new DefaultListModel();
    List<DefaultListModel<String>> itemsConjuntos = new ArrayList();
    DefaultListModel<String> nombresAcciones = new DefaultListModel();
    List<DefaultListModel<String>> itemsAcciones = new ArrayList();
    List<DefaultTableModel> FirstLastTokens = new ArrayList();
    List<DefaultTableModel> FollowTokens = new ArrayList();
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSeleccionarArchivo = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        tpDatos = new javax.swing.JTabbedPane();
        tbConjuntos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNombreConjuntos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstItemsConjuntos = new javax.swing.JList<>();
        tbTokens = new javax.swing.JPanel();
        cbTokens = new javax.swing.JComboBox<>();
        lblExpresionRegular = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        FirstLastTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        FollowTable = new javax.swing.JTable();
        tbAcciones = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstNombreItemAccion = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstContenidoItemAccion = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        tbError = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSeleccionarArchivo.setText("Seleccione su archivo");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        lblArchivo.setText("Nombre del archivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSeleccionarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblArchivo)
                .addContainerGap())
        );

        lstNombreConjuntos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNombreConjuntosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstNombreConjuntos);

        lstItemsConjuntos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstItemsConjuntos);

        javax.swing.GroupLayout tbConjuntosLayout = new javax.swing.GroupLayout(tbConjuntos);
        tbConjuntos.setLayout(tbConjuntosLayout);
        tbConjuntosLayout.setHorizontalGroup(
            tbConjuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbConjuntosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        tbConjuntosLayout.setVerticalGroup(
            tbConjuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbConjuntosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(tbConjuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        tpDatos.addTab("Conjuntos", tbConjuntos);

        cbTokens.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTokensItemStateChanged(evt);
            }
        });

        lblExpresionRegular.setText("jLabel1");

        FirstLastTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(FirstLastTable);

        jTabbedPane1.addTab("First y Last", jScrollPane4);

        FollowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(FollowTable);

        jTabbedPane1.addTab("Follow", jScrollPane7);

        javax.swing.GroupLayout tbTokensLayout = new javax.swing.GroupLayout(tbTokens);
        tbTokens.setLayout(tbTokensLayout);
        tbTokensLayout.setHorizontalGroup(
            tbTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbTokensLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(tbTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbTokens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExpresionRegular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        tbTokensLayout.setVerticalGroup(
            tbTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbTokensLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cbTokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblExpresionRegular)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        tpDatos.addTab("Tokens", tbTokens);

        lstNombreItemAccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNombreItemAccion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNombreItemAccionValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstNombreItemAccion);

        lstContenidoItemAccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstContenidoItemAccion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstContenidoItemAccionValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(lstContenidoItemAccion);

        jScrollPane3.setEnabled(false);

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane3.setViewportView(txtContenido);

        javax.swing.GroupLayout tbAccionesLayout = new javax.swing.GroupLayout(tbAcciones);
        tbAcciones.setLayout(tbAccionesLayout);
        tbAccionesLayout.setHorizontalGroup(
            tbAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbAccionesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(tbAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addGroup(tbAccionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        tbAccionesLayout.setVerticalGroup(
            tbAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbAccionesLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(tbAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tpDatos.addTab("Acciones", tbAcciones);

        lblError.setText("Número de error: ");

        javax.swing.GroupLayout tbErrorLayout = new javax.swing.GroupLayout(tbError);
        tbError.setLayout(tbErrorLayout);
        tbErrorLayout.setHorizontalGroup(
            tbErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblError)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        tbErrorLayout.setVerticalGroup(
            tbErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblError)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        tpDatos.addTab("Error", tbError);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpDatos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpDatos))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        FileDialog fileDialog = new FileDialog(this, "Seleccione un archivo", FileDialog.LOAD);
        fileDialog.setVisible(true);
        String archivo = fileDialog.getFile();
        if (archivo == null)
        {
            lblArchivo.setText("No se seleeciono archivo");
        }
        else
        {
            String ubicacion = fileDialog.getDirectory();
            lblArchivo.setText(fileDialog.getFile());
            try {
                Globales.Caracteres = 1; Globales.Linea = 1;
                Tokens = new ArrayList();
                Conjuntos = new ArrayList();
                Acciones = new ArrayList();
                nombreConjuntos = new DefaultListModel();
                itemsConjuntos = new ArrayList();
                nombresAcciones = new DefaultListModel();
                itemsAcciones = new ArrayList();
                cbTokens.removeAllItems();
                txtContenido.setText("");
                CargarArchivo cargar = new CargarArchivo(fileDialog.getDirectory() + fileDialog.getFile());
                // Carga los conjuntos a las listas
                if (Conjuntos.size() > 0)
                {
                    for (int i = 0; i < Conjuntos.size(); i++)
                    {
                        nombreConjuntos.addElement(Conjuntos.get(i).getNombre());
                        itemsConjuntos.add(new DefaultListModel<String>());
                        for (int j = 0; j < Conjuntos.get(i).Contenido.size(); j++)
                        {
                            itemsConjuntos.get(i).addElement(String.valueOf(Conjuntos.get(i).getContenido(j)));
                        }
                    }
                    lstNombreConjuntos.setModel(nombreConjuntos);
                    lstNombreConjuntos.setSelectedIndex(0);
                    lstItemsConjuntos.setModel(itemsConjuntos.get(0));
                }
                // Carga los tokens a las listas
                if (Tokens.size() > 0)
                {
                    String[] columnas = {"Item", "First", "Last"};
                    String[] columnasF = {"Item", "Follow"};
                    String[][] datos = null;
                    String[][] datosFollow = null;
                    for (int i = 0; i < Tokens.size(); i++)
                    {
                        cbTokens.addItem(Tokens.get(i).getNombre());
                        expresionRegularCompleta.add(new ExpresionCompleta(Tokens.get(i).getExpresionRegular()));
                        datos = new String[expresionRegularCompleta.get(i).nodos.size()][columnas.length];
                        datosFollow = new String[expresionRegularCompleta.get(i).Follow.size()][columnasF.length];
                        for (int j = 0; j < expresionRegularCompleta.get(i).nodos.size(); j++)
                        {
                            datos[j][0] = expresionRegularCompleta.get(i).nodos.get(j).Valor;
                            datos[j][1] = expresionRegularCompleta.get(i).nodos.get(j).FirstString();
                            datos[j][2] = expresionRegularCompleta.get(i).nodos.get(j).LastString();
                        }
                        for (int j = 0; j < expresionRegularCompleta.get(i).Follow.size(); j++)
                        {
                            datosFollow[j][0] = String.valueOf(expresionRegularCompleta.get(i).Follow.get(j).Dato);
                            datosFollow[j][1] = expresionRegularCompleta.get(i).Follow.get(j).ProduccionesString();
                        }
                        FirstLastTokens.add(new DefaultTableModel(datos, columnas));
                        FollowTokens.add(new DefaultTableModel(datosFollow, columnasF));
                    }
                    lblExpresionRegular.setText(Tokens.get(0).getExpresionRegular());
                    FirstLastTable.setModel(FirstLastTokens.get(0));
                    FollowTable.setModel(FollowTokens.get(0));
                    
                }
                // Carga las acciones
                if (Acciones.size() > 0)
                {
                    for (int i = 0; i < Acciones.size(); i++)
                    {
                        nombresAcciones.addElement(Acciones.get(i).getNombre());
                        itemsAcciones.add(new DefaultListModel<String>());
                        for (int j = 0; j < Acciones.get(i).Items.size(); j++)
                        {
                            itemsAcciones.get(i).addElement(Acciones.get(i).Items.get(j).getID());
                        }
                    }
                    lstNombreItemAccion.setModel(nombresAcciones);
                    lstNombreItemAccion.setSelectedIndex(0);
                    lstContenidoItemAccion.setModel(itemsAcciones.get(0));
                }
                // Carga el error
                lblError.setText("Número de error: " + Error.getNumero());
                CodificarCSharp cSharp = new CodificarCSharp(ubicacion);
                CodificarCPlusPlus cPP = new CodificarCPlusPlus(ubicacion);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex, "Error", HEIGHT);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void lstNombreConjuntosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNombreConjuntosValueChanged
        try
        {
            int actual = lstNombreConjuntos.getSelectedIndex();
            lstItemsConjuntos.setModel(itemsConjuntos.get(actual));
        }
        catch (Exception ex)
        {
            
        }
    }//GEN-LAST:event_lstNombreConjuntosValueChanged

    private void cbTokensItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTokensItemStateChanged
        try
        {
            int actual = cbTokens.getSelectedIndex();
            lblExpresionRegular.setText(Tokens.get(actual).getExpresionRegular());
            FirstLastTable.setModel(FirstLastTokens.get(actual));
            FollowTable.setModel(FollowTokens.get(actual));
        }
        catch (Exception ex)
        {
            
        }
    }//GEN-LAST:event_cbTokensItemStateChanged

    private void lstNombreItemAccionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNombreItemAccionValueChanged
        try
        {
            int actual = lstNombreItemAccion.getSelectedIndex();
            lstContenidoItemAccion.setModel(itemsAcciones.get(actual));
        }
        catch (Exception ex)
        {
            
        }
    }//GEN-LAST:event_lstNombreItemAccionValueChanged

    private void lstContenidoItemAccionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstContenidoItemAccionValueChanged
        try
        {
            int actualContenido = lstContenidoItemAccion.getSelectedIndex();
            int actualNombre = lstNombreItemAccion.getSelectedIndex();
            txtContenido.setText(Acciones.get(actualNombre).Items.get(actualContenido).getContenido());
        }
        catch (Exception ex)
        {
            
        }
    }//GEN-LAST:event_lstContenidoItemAccionValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FirstLastTable;
    private javax.swing.JTable FollowTable;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JComboBox<String> cbTokens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblExpresionRegular;
    private javax.swing.JList<String> lstContenidoItemAccion;
    private javax.swing.JList<String> lstItemsConjuntos;
    private javax.swing.JList<String> lstNombreConjuntos;
    private javax.swing.JList<String> lstNombreItemAccion;
    private javax.swing.JPanel tbAcciones;
    private javax.swing.JPanel tbConjuntos;
    private javax.swing.JPanel tbError;
    private javax.swing.JPanel tbTokens;
    private javax.swing.JTabbedPane tpDatos;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
